run:
  name: "" # use this to keep track of runs with different settings

# any of:
# - pypsa (output from PyPSA-Eur: https://pypsa-eur.readthedocs.io/en/latest/)
source: pypsa

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

bidding_zones: ['DK_2', 'FI', 'NO', 'SE']

bidding_zones_in_country:
  'DK': ['DK_2']
  'FI': ['FI']
  'NO': ['NO_1', 'NO_2', 'NO_3', 'NO_4', 'NO_5']
  'SE': ['SE_1', 'SE_2', 'SE_3', 'SE_4']

year: 2015

M_base: 100 # power base for p.u. calculations

generator_p_min: 5  # MW

snapshots:  # either percentage or snapshot is required, normally only percentage is specified
  high:
    percentage: null # percentage on the load duration curve
    snapshot: '2015-02-14 16:00:00' # UTC
  low:
    percentage: null
    snapshot: '2015-07-03 19:00:00' # UTC

build_network:
  exclude_under_construction: False
  supress_psse_output: True
  slack_buses: ["6591"]  # centralized nuclear plant

database:
  buses:
    - v_nom
    - symbol
    - under_construction
    - x
    - y
    - carrier
    - country
    - bidding_zone
    - in_synchronous_network
  generators:
    - bus
    - name
    - type
    - p_nom
    - p_nom_max
    - p_nom_min
    - p_max_pu
    - p_min_pu
    - p_set
    - q_set
  storage_units:
    - bus
    - type
    - p_nom
    - p_nom_max
    - p_max_pu
    - p_min_pu
    - p_set
    - q_set
  loads:
    - bus
    - p_set
    - q_set
  shunt_impedances:
    - bus
    - g_pu
    - b_pu
  lines:
    - bus0
    - bus1
    - num_parallel
    - length
    - under_construction
    - s_max_pu
    - s_nom
    - x_pu
    - r_pu
    - g_pu
    - b_pu
  links:
    - bus0
    - bus1
    - length
    - under_construction
    - p_nom
    - p_set
  transformers:
    - bus0
    - bus1
    - s_nom
    - x_pu
    - r_pu
    - g_pu
    - b_pu
  external_links:
    - bus
    - bus_outside
    - link
    - p_set
    - q_set

generation:
  pypsa_map:
    PHS: hydro
    hydro: hydro
    ror: hydro
    nuclear: nuclear
    onwind: wind-onshore
    offwind-dc: wind-offshore
    solar: solar
    offwind-ac: wind-offshore

  entsoe_map:
    Nuclear: nuclear
    Wind Onshore: wind-onshore
    Geothermal: other
    Hydro Run-of-river and poundage: hydro
    Hydro Water Reservoir: hydro
    Wind Offshore: wind-offshore
    Hydro Pumped Storage: hydro
    Solar: solar

# https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_authentication_and_authorisation
entsoe:
  security_token: fe5dbb25-46fd-4a4b-a19c-d3d0772e00d5

# make sure each connection is there only once -> so if DK->NO is defined, dont define NO->DK also
external_links:
  'FI': ['EE', 'NO', 'RU', 'SE', 'SE_3']  # add SE3 area here for DC-link data
  'NO': ['DK_1', 'DE', 'NL', 'GB']
  'SE': ['DK_1', 'DE', 'LT', 'PL']
  'DK_2': ['DK_1', 'DE_AT_LU', 'DE_LU']

bidding_zone_map:
  SE_3: SE  # only DK has bidding zone info in the database at the moment