run:
  input: "2020"
  name: "hl_hw" # use this to keep track of runs with different settings

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

countries: ['DK', 'FI', 'NO', 'SE']
bidding_zones: ['DK_2', 'FI', 'NO_1', 'NO_2', 'NO_3', 'NO_4', 'NO_5', 'SE_1', 'SE_2', 'SE_3', 'SE_4']

bidding_zones_in_country:
  'DK': ['DK_1', 'DK_2']
  'FI': ['FI']
  'NO': ['NO_1', 'NO_2', 'NO_3', 'NO_4', 'NO_5']
  'SE': ['SE_1', 'SE_2', 'SE_3', 'SE_4']

regions: ['Not in any region', 'Agder', 'Gävleborgs', 'Skåne', 'Gotlands', 'Västra Götalands', 'Hallands', 'Östergötlands',
          'Jönköpings', 'Kalmar', 'Kronobergs', 'Blekinge', 'Rogaland','Södra Savolax', 'Satakunta', 'Kymmenedalen', 'Egentliga Finland',
          'Egentliga Tavastland', 'Birkaland', 'Nyland', 'Södra Karelen', 'Uppsala', 'Södermanlands', 'Stockholms', 'Viken','Värmlands',
          'Dalarnas', 'Örebro', 'Västmanlands', 'Vestland', 'Vestfold og Telemark', 'Innlandet', 'Oslo', 'Mellersta Österbotten',
          'Norra Österbotten', 'Södra Österbotten', 'Mellersta Finland','Kajanaland', 'Norra Savolax', 'Västerbottens', 'Västernorrlands',
          'Österbotten', 'Trøndelag', 'Jämtlands', 'Møre og Romsdal', 'Norrbottens', 'Lappland', 'Nordland', 'Troms og Finnmark']

regions_in_country:
  'FI': ['Lappland', 'Norra Österbotten', 'Kajanaland', 'Norra Savolax', 'Södra Savolax', 'Södra Karelen', 'Mellersta Finland',
         'Södra Österbotten','Österbotten', 'Mellersta Österbotten', 'Birkaland', 'Satakunta', 'Egentliga Tavastland', 'Kymmenedalen',
         'Nyland', 'Egentliga Finland']
  'SE': ['Blekinge', 'Dalarnas', 'Gotlands', 'Gävleborgs', 'Hallands', 'Jämtlands', 'Jönköpings', 'Kalmar', 'Kronobergs', 'Norrbottens',
         'Skåne', 'Stockholms', 'Södermanlands', 'Uppsala','Värmlands', 'Västerbottens', 'Västernorrlands', 'Västmanlands', 'Västra Götalands',
         'Örebro', 'Östergötlands']
  'NO': ['Oslo', 'Rogaland', 'Møre og Romsdal', 'Nordland', 'Viken', 'Innlandet', 'Vestfold og Telemark', 'Agder', 'Vestland', 'Trøndelag',
         'Troms og Finnmark']

M_base: 100 # power base for p.u. calculations

generator_p_min: 5  # MW

# This is an estimate that should be improved iteratively
#hw_hl
#losses:  # From PSS/E
#  DK_2: 9
#  FI: 220
#  NO_1: 78
#  NO_2: 47
#  NO_3: 23
#  NO_4: 19
#  NO_5: 18
#  SE_1: 18
#  SE_2: 225
#  SE_3: 266
#  SE_4: 131

##ll_hw
losses:
  DK_2: 2
  FI: 52
  NO_1: 31
  NO_2: 51
  NO_3: 27
  NO_4: 20
  NO_5: 34
  SE_1: 6
  SE_2: 87
  SE_3: 128
  SE_4: 66

#ll_lw
#losses:
#  DK_2: 3
#  FI: 158
#  NO_1: 60
#  NO_2: 51
#  NO_3: 17
#  NO_4: 21
#  NO_5: 30
#  SE_1: 33
#  SE_2: 259
#  SE_3: 228
#  SE_4: 120

#hl_lw
#losses:
#   DK_2: 4
#   FI: 151
#   NO_1: 152
#   NO_2: 77
#   NO_3: 48
#   NO_4: 59
#   NO_5: 54
#   SE_1: 34
#   SE_2: 557
#   SE_3: 475
#   SE_4: 126


# Watch out with availability of data in ENTSO-E
# e.g. Between 14.10.2019 07:00 and 03.03.2020 10:00, there is no data on cross-flow NO1-NO2
#2020-high
#snapshot: '2020-03-04 18:00:00'

#ll_hw
snapshot: '2020-09-17 00:00'

#ll_lw
#snapshot: '2020-08-01 05:00'

#hl_hw
#snapshot: '2020-02-21 18:00'

#hl_lw
#snapshot: '2020-02-27 18:00'

build_network:
  scheduled_voltage: 1.0  # pu
  exclude_under_construction: False
  supress_psse_output: True
  slack_buses: ["6585"]  # centralized nuclear plant
#  slack_buses: ["7003"]  # biggest hydro plant in SE_1

database:
  buses:
    - v_nom
    - symbol
    - under_construction
    - x
    - y
    - carrier
    - country
    - bidding_zone
    - in_synchronous_network
  generators:
    - bus
    - name
    - type
    - p_nom
    - p_nom_max
    - p_nom_min
    - p_max_pu
    - p_min_pu
    - p_set
    - q_set
  storage_units:
    - bus
    - type
    - p_nom
    - p_nom_max
    - p_max_pu
    - p_min_pu
    - p_set
    - q_set
  loads:
    - bus
    - p_set
    - q_set
  shunt_impedances:
    - bus
    - g_pu
    - b_pu
    - bl1_steps
    - bl1_mva
    - bl2_steps
    - bl2_mva
    - v_high
    - v_low
  lines:
    - bus0
    - bus1
    - num_parallel
    - length
    - under_construction
    - s_max_pu
    - s_nom
    - s_nom_2
    - x_pu
    - r_pu
    - g_pu
    - b_pu
  links:
    - bus0
    - bus1
    - length
    - under_construction
    - p_nom
    - p_set
  transformers:
    - bus0
    - bus1
    - s_nom
    - x_pu
    - r_pu
    - g_pu
    - b_pu
  external_links:
    - bus
    - bus_outside
    - link
    - p_set
    - q_set

generation:
  pypsa_map:
    PHS: hydro
    hydro: hydro
    ror: hydro
    nuclear: nuclear
    onwind: wind-onshore
    offwind-dc: wind-offshore
    solar: solar
    offwind-ac: wind-offshore

  entsoe_map:
    Nuclear: nuclear
    Wind Onshore: wind-onshore
    Geothermal: other
    Hydro Run-of-river and poundage: hydro
    Hydro Water Reservoir: hydro
    Wind Offshore: wind-offshore
    Hydro Pumped Storage: hydro
    Solar: solar

# https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_authentication_and_authorisation
entsoe:
  security_token: fe5dbb25-46fd-4a4b-a19c-d3d0772e00d5


#cross_border_flows:
#  'FI': ['EE', 'NO_4', 'RU', 'SE_1', 'SE_3']
#  'NO': ['DK_1', 'DE', 'NL', 'GB', 'SE']
#  'SE': ['DK_1', 'DK_2', 'DE', 'LT', 'PL']
#  'DK_2': ['DK_1', 'DE_AT_LU', 'DE_LU']